/*
03yxzwbgz3tvd 1254916709

explain plan for INSERT  INTO GP_TEMP_RICERCA_AGENDE ( ID_PRESTAZIONE, ID_AZIENDA_SANITARIA, ID_PRESIDIO, ID_REPARTO, ID_UNITA_EROGANTE, CD_UNITA_PRENOTANTE, ID_AGENDA, ID_PRESTAZIONE_AGENDA, ID_COMBINATA, FL_V
INCOLI_RISPETTATI ) -- SELECT opt_param('_fix_control' '8560951:on') opt_param('optimizer_features_enable' '11.2.0.2') DISTINCT          PA.ID_PRESTAZIONE, PA.ID_AZIENDA_SANITARIA, PA.ID_PRESIDIO, PA.ID_
REPARTO, PA.ID_UNITA_EROGANTE, PA.CD_UNITA_PRENOTANTE, PA.ID_AGENDA, PA.ID_PRESTAZIONE_AGENDA, PA.ID_COMBINATA, 'S'   FROM GP_TEMP_RA_PRESCRIZIONI RA   INNER JOIN V_GP_PRESTAZIONI_AGENDE PA ON RA.ID_PRESTAZIONE
=PA.ID_PRESTAZIONE INNER JOIN GP_AGENDE AG ON PA.ID_AGENDA=AG.ID_AGENDA --   WHERE ( EXISTS (                    SELECT 0
             FROM V_GP_DISTRETTI_PA DP                      INNER JOIN GP_DISTRETTI_ANATOMICI DA ON DP.ID_DISTRETTO_ANATOMICO=DA.ID_DISTRETTO_ANATOMICO
*/

alter session set "_fix_control"='12341619:off','8560951:on';


var res number
exec :res := dbms_spm.load_plans_from_cursor_cache( sql_id => '03yxzwbgz3tvd', plan_hash_value => 1254916709, sql_handle => '&sql_handle');

