@set

explain plan for
INSERT 
  /*+
      BEGIN_OUTLINE_DATA
      IGNORE_OPTIM_EMBEDDED_HINTS
      OPTIMIZER_FEATURES_ENABLE('11.2.0.2')
      DB_VERSION('11.2.0.2')
      OPT_PARAM('_complex_view_merging' 'false')
      ALL_ROWS
      FORCE_XML_QUERY_REWRITE
      XML_DML_RWT_STMT
      XMLINDEX_REWRITE
      XMLINDEX_REWRITE_IN_SELECT
      NO_COST_XML_QUERY_REWRITE
      OUTLINE_LEAF(@"SEL$D99AE0CE")
      MERGE(@"SEL$74")
      OUTLINE_LEAF(@"SEL$72")
      OUTLINE_LEAF(@"SEL$135E0F46")
      MERGE(@"SEL$117FC0EF")
      OUTLINE_LEAF(@"SEL$29445BC0")
      MERGE(@"SEL$83F593D9")
      OUTLINE_LEAF(@"SEL$4A493674")
      MERGE(@"SEL$77")
      OUTLINE_LEAF(@"SEL$05F70FAB")
      MERGE(@"SEL$82")
      OUTLINE_LEAF(@"SEL$79")
      OUTLINE_LEAF(@"SEL$85")
      OUTLINE_LEAF(@"SEL$007F748F")
      MERGE(@"SEL$17190F20")
      OUTLINE_LEAF(@"SEL$87")
      OUTLINE_LEAF(@"SEL$3B22806E")
      MERGE(@"SEL$8AC8429B")
      OUTLINE_LEAF(@"SEL$9F6E67B7")
      MERGE(@"SEL$729E278B")
      OUTLINE_LEAF(@"SEL$580484EB")
      MERGE(@"SEL$E34B3CBC")
      OUTLINE_LEAF(@"SEL$AA364CFE")
      ELIMINATE_JOIN(@"SEL$C4D78204" "QD"@"SEL$26")
      OUTLINE_LEAF(@"SEL$32")
      OUTLINE_LEAF(@"SEL$33")
      OUTLINE_LEAF(@"SET$1")
      OUTLINE_LEAF(@"SEL$31")
      OUTLINE_LEAF(@"SEL$30")
      OUTLINE_LEAF(@"SEL$0B56E548")
      MERGE(@"SEL$0C87BDE4")
      OUTLINE_LEAF(@"SEL$41")
      OUTLINE_LEAF(@"SEL$42")
      OUTLINE_LEAF(@"SET$2")
      OUTLINE_LEAF(@"SEL$40")
      OUTLINE_LEAF(@"SEL$39")
      OUTLINE_LEAF(@"SEL$3CF8A339")
      MERGE(@"SEL$D92DD8A6")
      OUTLINE_LEAF(@"SEL$6E8A1281")
      MERGE(@"SEL$0CC14547")
      OUTLINE_LEAF(@"SEL$054DEA08")
      MERGE(@"SEL$97")
      OUTLINE_LEAF(@"SEL$1BF21858")
      MERGE(@"SEL$E413913A")
      OUTLINE_LEAF(@"SEL$110")
      OUTLINE_LEAF(@"SEL$111")
      OUTLINE_LEAF(@"SEL$3B9BC654")
      MERGE(@"SEL$100")
      OUTLINE_LEAF(@"SEL$A813CFE0")
      UNNEST(@"SEL$113")
      OUTLINE_LEAF(@"SEL$115")
      OUTLINE_LEAF(@"SEL$F20B9ADE")
      MERGE(@"SEL$117")
      OUTLINE_LEAF(@"SEL$FC6FDB48")
      MERGE(@"SEL$119")
      OUTLINE_LEAF(@"SEL$89C8337D")
      MERGE(@"SEL$121")
      OUTLINE_LEAF(@"SEL$ECFFA1E1")
      MERGE(@"SEL$123")
      OUTLINE_LEAF(@"SEL$D286CFDD")
      MERGE(@"SEL$125")
      OUTLINE_LEAF(@"SEL$C1A1C340")
      MERGE(@"SEL$127")
      OUTLINE_LEAF(@"SEL$C2C95986")
      MERGE(@"SEL$129")
      OUTLINE_LEAF(@"SEL$EB48DB44")
      MERGE(@"SEL$131")
      OUTLINE_LEAF(@"SEL$4B65EFF4")
      MERGE(@"SEL$4CEA5FC3")
      OUTLINE_LEAF(@"SEL$133")
      OUTLINE_LEAF(@"SEL$ABE5A3DF")
      MERGE(@"SEL$53")
      OUTLINE_LEAF(@"SEL$36603176")
      MERGE(@"SEL$B30E91C6")
      OUTLINE_LEAF(@"SEL$66")
      OUTLINE_LEAF(@"SEL$67")
      OUTLINE_LEAF(@"SEL$1F9A5FEE")
      MERGE(@"SEL$56")
      OUTLINE_LEAF(@"SEL$96F347FF")
      UNNEST(@"SEL$114")
      UNNEST(@"SEL$AEEF7BBD")
      UNNEST(@"SEL$FB9B2C2B")
      OUTLINE_LEAF(@"INS$1")
      OUTLINE_LEAF(@"SEL$115_1")
      USE_CONCAT(@"SEL$115" 8 OR_PREDICATES(2))
      OUTLINE_LEAF(@"SEL$115_2")
      OUTLINE(@"SEL$73")
      OUTLINE(@"SEL$74")
      OUTLINE(@"SEL$71")
      OUTLINE(@"SEL$117FC0EF")
      MERGE(@"SEL$F5BB74E1")
      OUTLINE(@"SEL$75")
      OUTLINE(@"SEL$83F593D9")
      MERGE(@"SEL$7286615E")
      OUTLINE(@"SEL$76")
      OUTLINE(@"SEL$77")
      OUTLINE(@"SEL$421141D5")
      MERGE(@"SEL$0130D9E3")
      OUTLINE(@"SEL$82")
      OUTLINE(@"SEL$86")
      OUTLINE(@"SEL$17190F20")
      MERGE(@"SEL$15")
      MERGE(@"SEL$16")
      OUTLINE(@"SEL$88")
      OUTLINE(@"SEL$8AC8429B")
      MERGE(@"SEL$DC4B4145")
      OUTLINE(@"SEL$89")
      OUTLINE(@"SEL$729E278B")
      MERGE(@"SEL$5EC70623")
      OUTLINE(@"SEL$90")
      OUTLINE(@"SEL$E34B3CBC")
      MERGE(@"SEL$43F09110")
      OUTLINE(@"SEL$C4D78204")
      MERGE(@"SEL$FFAA604D")
      OUTLINE(@"SEL$92")
      OUTLINE(@"SEL$0C87BDE4")
      MERGE(@"SEL$5F84C75E")
      OUTLINE(@"SEL$93")
      OUTLINE(@"SEL$D92DD8A6")
      MERGE(@"SEL$A7416263")
      OUTLINE(@"SEL$94")
      OUTLINE(@"SEL$0CC14547")
      MERGE(@"SEL$03AE7C5B")
      OUTLINE(@"SEL$108")
      OUTLINE(@"SEL$97")
      OUTLINE(@"SEL$109")
      OUTLINE(@"SEL$E413913A")
      MERGE(@"SEL$98")
      OUTLINE(@"SEL$112")
      OUTLINE(@"SEL$100")
      OUTLINE(@"SEL$B717064A")
      MERGE(@"SEL$BCB8ECD4")
      OUTLINE(@"SEL$113")
      OUTLINE(@"SEL$116")
      OUTLINE(@"SEL$117")
      OUTLINE(@"SEL$118")
      OUTLINE(@"SEL$119")
      OUTLINE(@"SEL$120")
      OUTLINE(@"SEL$121")
      OUTLINE(@"SEL$122")
      OUTLINE(@"SEL$123")
      OUTLINE(@"SEL$124")
      OUTLINE(@"SEL$125")
      OUTLINE(@"SEL$126")
      OUTLINE(@"SEL$127")
      OUTLINE(@"SEL$128")
      OUTLINE(@"SEL$129")
      OUTLINE(@"SEL$130")
      OUTLINE(@"SEL$131")
      OUTLINE(@"SEL$132")
      OUTLINE(@"SEL$4CEA5FC3")
      MERGE(@"SEL$49")
      OUTLINE(@"SEL$64")
      OUTLINE(@"SEL$53")
      OUTLINE(@"SEL$65")
      OUTLINE(@"SEL$B30E91C6")
      MERGE(@"SEL$54")
      OUTLINE(@"SEL$68")
      OUTLINE(@"SEL$56")
      OUTLINE(@"SEL$DD112277")
      MERGE(@"SEL$4C7AC304")
      OUTLINE(@"SEL$114")
      OUTLINE(@"SEL$AEEF7BBD")
      MERGE(@"SEL$10")
      OUTLINE(@"SEL$FB9B2C2B")
      MERGE(@"SEL$135")
      OUTLINE(@"SEL$115")
      OUTLINE(@"SEL$3")
      OUTLINE(@"SEL$F5BB74E1")
      MERGE(@"SEL$2")
      OUTLINE(@"SEL$6")
      OUTLINE(@"SEL$7286615E")
      MERGE(@"SEL$5")
      OUTLINE(@"SEL$80")
      OUTLINE(@"SEL$0130D9E3")
      MERGE(@"SEL$8269FC7D")
      OUTLINE(@"SEL$14")
      OUTLINE(@"SEL$15")
      OUTLINE(@"SEL$16")
      OUTLINE(@"SEL$19")
      OUTLINE(@"SEL$DC4B4145")
      MERGE(@"SEL$18")
      OUTLINE(@"SEL$22")
      OUTLINE(@"SEL$5EC70623")
      MERGE(@"SEL$21")
      OUTLINE(@"SEL$25")
      OUTLINE(@"SEL$43F09110")
      MERGE(@"SEL$24")
      OUTLINE(@"SEL$91")
      OUTLINE(@"SEL$FFAA604D")
      MERGE(@"SEL$27")
      OUTLINE(@"SEL$36")
      OUTLINE(@"SEL$5F84C75E")
      MERGE(@"SEL$35")
      MERGE(@"SEL$6BD15B31")
      OUTLINE(@"SEL$45")
      OUTLINE(@"SEL$A7416263")
      MERGE(@"SEL$44")
      MERGE(@"SEL$62725911")
      OUTLINE(@"SEL$48")
      OUTLINE(@"SEL$03AE7C5B")
      MERGE(@"SEL$47")
      OUTLINE(@"SEL$99")
      OUTLINE(@"SEL$98")
      OUTLINE(@"SEL$95")
      OUTLINE(@"SEL$BCB8ECD4")
      MERGE(@"SEL$E524D37F")
      OUTLINE(@"SEL$50")
      OUTLINE(@"SEL$49")
      OUTLINE(@"SEL$55")
      OUTLINE(@"SEL$54")
      OUTLINE(@"SEL$70")
      OUTLINE(@"SEL$4C7AC304")
      MERGE(@"SEL$8D9782D5")
      OUTLINE(@"SEL$3700BE85")
      MERGE(@"SEL$4B3CBED7")
      OUTLINE(@"SEL$10")
      OUTLINE(@"SEL$134")
      OUTLINE(@"SEL$135")
      OUTLINE(@"SEL$1")
      OUTLINE(@"SEL$2")
      OUTLINE(@"SEL$4")
      OUTLINE(@"SEL$5")
      OUTLINE(@"SEL$84")
      OUTLINE(@"SEL$8269FC7D")
      MERGE(@"SEL$81")
      OUTLINE(@"SEL$17")
      OUTLINE(@"SEL$18")
      OUTLINE(@"SEL$20")
      OUTLINE(@"SEL$21")
      OUTLINE(@"SEL$23")
      OUTLINE(@"SEL$24")
      OUTLINE(@"SEL$26")
      OUTLINE(@"SEL$27")
      OUTLINE(@"SEL$34")
      OUTLINE(@"SEL$35")
      OUTLINE(@"SEL$6BD15B31")
      MERGE(@"SEL$29")
      OUTLINE(@"SEL$43")
      OUTLINE(@"SEL$44")
      OUTLINE(@"SEL$62725911")
      MERGE(@"SEL$38")
      OUTLINE(@"SEL$46")
      OUTLINE(@"SEL$47")
      OUTLINE(@"SEL$96")
      OUTLINE(@"SEL$E524D37F")
      MERGE(@"SEL$F79E0988")
      OUTLINE(@"SEL$69")
      OUTLINE(@"SEL$8D9782D5")
      MERGE(@"SEL$4AD9722C")
      OUTLINE(@"SEL$78")
      OUTLINE(@"SEL$4B3CBED7")
      MERGE(@"SEL$DCE09009")
      OUTLINE(@"SEL$83")
      OUTLINE(@"SEL$81")
      OUTLINE(@"SEL$28")
      OUTLINE(@"SEL$29")
      OUTLINE(@"SEL$37")
      OUTLINE(@"SEL$38")
      OUTLINE(@"SEL$107")
      OUTLINE(@"SEL$F79E0988")
      MERGE(@"SEL$78C1D3B5")
      OUTLINE(@"SEL$51")
      OUTLINE(@"SEL$4AD9722C")
      MERGE(@"SEL$DBDFA7B7")
      OUTLINE(@"SEL$13")
      OUTLINE(@"SEL$DCE09009")
      MERGE(@"SEL$7")
      MERGE(@"SEL$D480BE77")
      OUTLINE(@"SEL$106")
      OUTLINE(@"SEL$78C1D3B5")
      MERGE(@"SEL$B2601B98")
      OUTLINE(@"SEL$52")
      OUTLINE(@"SEL$DBDFA7B7")
      MERGE(@"SEL$AF6A6795")
      OUTLINE(@"SEL$8")
      OUTLINE(@"SEL$7")
      OUTLINE(@"SEL$D480BE77")
      MERGE(@"SEL$AD16910F")
      OUTLINE(@"SEL$105")
      OUTLINE(@"SEL$B2601B98")
      MERGE(@"SEL$51044E2C")
      OUTLINE(@"SEL$63")
      OUTLINE(@"SEL$AF6A6795")
      MERGE(@"SEL$D3C5AC05")
      OUTLINE(@"SEL$12")
      OUTLINE(@"SEL$AD16910F")
      MERGE(@"SEL$9")
      OUTLINE(@"SEL$104")
      OUTLINE(@"SEL$51044E2C")
      MERGE(@"SEL$66CBEF8A")
      OUTLINE(@"SEL$62")
      OUTLINE(@"SEL$D3C5AC05")
      MERGE(@"SEL$08A0392E")
      OUTLINE(@"SEL$11")
      OUTLINE(@"SEL$9")
      OUTLINE(@"SEL$103")
      OUTLINE(@"SEL$66CBEF8A")
      MERGE(@"SEL$101")
      OUTLINE(@"SEL$61")
      OUTLINE(@"SEL$08A0392E")
      MERGE(@"SEL$1AB05C7F")
      OUTLINE(@"SEL$102")
      OUTLINE(@"SEL$101")
      OUTLINE(@"SEL$60")
      OUTLINE(@"SEL$1AB05C7F")
      MERGE(@"SEL$53EDC8E6")
      OUTLINE(@"SEL$59")
      OUTLINE(@"SEL$53EDC8E6")
      MERGE(@"SEL$57")
      OUTLINE(@"SEL$58")
      OUTLINE(@"SEL$57")
      FULL(@"INS$1" "GP_TEMP_RICERCA_AGENDE"@"INS$1")
      INDEX(@"SEL$96F347FF" "RA"@"SEL$51" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$96F347FF" "PA"@"SEL$57" ("GP_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE"))
      INDEX_RS_ASC(@"SEL$96F347FF" "AG"@"SEL$57" ("GP_AGENDE"."ID_AGENDA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "AG"@"SEL$69" ("GP_AGENDE"."ID_AGENDA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "UE"@"SEL$58" ("GP_UNITA_EROGANTI"."ID_UNITA_EROGANTE"))
      INDEX_RS_ASC(@"SEL$96F347FF" "RE"@"SEL$60" ("GP_REPARTI"."ID_REPARTO"))
      INDEX_RS_ASC(@"SEL$96F347FF" "PR"@"SEL$61" ("GP_PRESIDI"."ID_PRESIDIO"))
      INDEX_RS_ASC(@"SEL$96F347FF" "AZ"@"SEL$62" ("GP_AZIENDE_SANITARIE"."ID_AZIENDA_SANITARIA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "PU"@"SEL$59" ("GP_PRESTAZIONI_UE"."ID_UNITA_EROGANTE"
              "GP_PRESTAZIONI_UE"."ID_PRESTAZIONE"))
      INDEX_RS_ASC(@"SEL$96F347FF" "PG"@"SEL$7" ("GP_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "PA"@"SEL$11" ("GP_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "MPA"@"SEL$10" ("GP_METODICHE_PRESTAZ_AGENDE"."ID_PRESTAZIONE_AGENDA"
              "GP_METODICHE_PRESTAZ_AGENDE"."DT_INIZIO_VALIDITA" "GP_METODICHE_PRESTAZ_AGENDE"."ID_METODICA"))
      INDEX(@"SEL$96F347FF" "ME"@"SEL$13" ("GP_METODICHE"."ID_METODICA"))
      INDEX_RS_ASC(@"SEL$96F347FF" "GP_CALENDARI_PA"@"SEL$135" ("GP_CALENDARI_PA"."ID_PRESTAZIONE_AGENDA"
              "GP_CALENDARI_PA"."ID_CALENDARIO"))
      INDEX_RS_ASC(@"SEL$96F347FF" "TE"@"SEL$7" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$96F347FF" "R2"@"SEL$114" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      LEADING(@"SEL$96F347FF" "RA"@"SEL$51" "PA"@"SEL$57" "AG"@"SEL$57" "AG"@"SEL$69" "UE"@"SEL$58"
              "RE"@"SEL$60" "PR"@"SEL$61" "AZ"@"SEL$62" "PU"@"SEL$59" "PG"@"SEL$7" "PA"@"SEL$11" "MPA"@"SEL$10"
              "ME"@"SEL$13" "GP_CALENDARI_PA"@"SEL$135" "TE"@"SEL$7" "R2"@"SEL$114")
      USE_NL(@"SEL$96F347FF" "PA"@"SEL$57")
      USE_NL(@"SEL$96F347FF" "AG"@"SEL$57")
      USE_NL(@"SEL$96F347FF" "AG"@"SEL$69")
      USE_NL(@"SEL$96F347FF" "UE"@"SEL$58")
      USE_NL(@"SEL$96F347FF" "RE"@"SEL$60")
      USE_NL(@"SEL$96F347FF" "PR"@"SEL$61")
      USE_NL(@"SEL$96F347FF" "AZ"@"SEL$62")
      USE_NL(@"SEL$96F347FF" "PU"@"SEL$59")
      USE_NL(@"SEL$96F347FF" "PG"@"SEL$7")
      USE_NL(@"SEL$96F347FF" "PA"@"SEL$11")
      USE_NL(@"SEL$96F347FF" "MPA"@"SEL$10")
      USE_NL(@"SEL$96F347FF" "ME"@"SEL$13")
      USE_NL(@"SEL$96F347FF" "GP_CALENDARI_PA"@"SEL$135")
      USE_NL(@"SEL$96F347FF" "TE"@"SEL$7")
      USE_NL(@"SEL$96F347FF" "R2"@"SEL$114")
      USE_HASH_AGGREGATION(@"SEL$96F347FF")
      PUSH_SUBQ(@"SEL$6E8A1281")
      PUSH_SUBQ(@"SEL$3CF8A339")
      PUSH_SUBQ(@"SEL$0B56E548")
      PUSH_SUBQ(@"SEL$AA364CFE")
      PUSH_SUBQ(@"SEL$580484EB")
      PUSH_SUBQ(@"SEL$9F6E67B7")
      PUSH_SUBQ(@"SEL$3B22806E")
      PUSH_SUBQ(@"SEL$87")
      PUSH_SUBQ(@"SEL$007F748F")
      PUSH_SUBQ(@"SEL$85")
      PUSH_SUBQ(@"SEL$A813CFE0")
      INDEX_RS_ASC(@"SEL$1F9A5FEE" "CO"@"SEL$56" ("COMUNI_RD"."CD_COMUNE_ISTAT"))
      INDEX(@"SEL$1F9A5FEE" "PO"@"SEL$56" ("PROVINCIE_RD"."PROV_KEY_ID"))
      LEADING(@"SEL$1F9A5FEE" "CO"@"SEL$56" "PO"@"SEL$56")
      USE_NL(@"SEL$1F9A5FEE" "PO"@"SEL$56")
      NLJ_BATCHING(@"SEL$1F9A5FEE" "PO"@"SEL$56")
      INDEX_RS_ASC(@"SEL$67" "CO"@"SEL$67" ("COMUNI_RD"."CD_COMUNE_ISTAT"))
      INDEX_RS_ASC(@"SEL$66" "UP"@"SEL$66" ("UNITA_PRENOTANTI"."CD_UNITA_PRENOTANTE"))
      INDEX_RS_ASC(@"SEL$36603176" "GP"@"SEL$54" ("GP_GIORNI_PA"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$36603176" "CA"@"SEL$54" ("GP_CALENDARI_PA"."ID_CALENDARIO_PA"))
      INDEX(@"SEL$36603176" "FR"@"SEL$55" ("GP_FASCE_RANGE_PA"."ID_GIORNO_PA"))
      LEADING(@"SEL$36603176" "GP"@"SEL$54" "CA"@"SEL$54" "FR"@"SEL$55")
      USE_NL(@"SEL$36603176" "CA"@"SEL$54")
      USE_NL(@"SEL$36603176" "FR"@"SEL$55")
      NLJ_BATCHING(@"SEL$36603176" "FR"@"SEL$55")
      INDEX_RS_ASC(@"SEL$ABE5A3DF" "RP"@"SEL$53" ("GP_RUOLI_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX(@"SEL$ABE5A3DF" "RU"@"SEL$53" ("GP_RUOLI"."ID_RUOLO"))
      LEADING(@"SEL$ABE5A3DF" "RP"@"SEL$53" "RU"@"SEL$53")
      USE_NL(@"SEL$ABE5A3DF" "RU"@"SEL$53")
      NLJ_BATCHING(@"SEL$ABE5A3DF" "RU"@"SEL$53")
      INDEX_RS_ASC(@"SEL$133" "DC"@"SEL$133" ("DISTANZA_COMUNI"."CD_COMUNE_ORIGINE"
              "DISTANZA_COMUNI"."CD_COMUNE_DESTINAZIONE"))
      INDEX_RS_ASC(@"SEL$4B65EFF4" "CA"@"SEL$50" ("V_DC_COMUNI_ASL_STORICO"."CD_COMUNE_ISTAT"))
      INDEX_RS_ASC(@"SEL$4B65EFF4" "CO"@"SEL$49" ("COMUNI_RD"."CD_COMUNE_ISTAT"))
      INDEX(@"SEL$4B65EFF4" "PR"@"SEL$49" ("PROVINCIE_RD"."PROV_KEY_ID"))
      LEADING(@"SEL$4B65EFF4" "CA"@"SEL$50" "CO"@"SEL$49" "PR"@"SEL$49")
      USE_NL(@"SEL$4B65EFF4" "CO"@"SEL$49")
      USE_NL(@"SEL$4B65EFF4" "PR"@"SEL$49")
      NLJ_BATCHING(@"SEL$4B65EFF4" "PR"@"SEL$49")
      FULL(@"SEL$EB48DB44" "KOKBF$"@"SEL$131")
      FULL(@"SEL$C2C95986" "KOKBF$"@"SEL$129")
      FULL(@"SEL$C1A1C340" "KOKBF$"@"SEL$127")
      FULL(@"SEL$D286CFDD" "KOKBF$"@"SEL$125")
      FULL(@"SEL$ECFFA1E1" "KOKBF$"@"SEL$123")
      FULL(@"SEL$89C8337D" "KOKBF$"@"SEL$121")
      FULL(@"SEL$FC6FDB48" "KOKBF$"@"SEL$119")
      FULL(@"SEL$F20B9ADE" "KOKBF$"@"SEL$117")
      INDEX_RS_ASC(@"SEL$115_1" "RP"@"SEL$115" ("GP_RUOLI_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$115_2" "RP"@"SEL$115_2" ("GP_RUOLI_PRESTAZIONI_AGENDE"."ID_RUOLO"
              "GP_RUOLI_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "AG"@"SEL$101" ("GP_AGENDE"."ID_AGENDA"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "UE"@"SEL$102" ("GP_UNITA_EROGANTI"."ID_UNITA_EROGANTE"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "RE"@"SEL$104" ("GP_REPARTI"."ID_REPARTO"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "PR"@"SEL$105" ("GP_PRESIDI"."ID_PRESIDIO"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "AZ"@"SEL$106" ("GP_AZIENDE_SANITARIE"."ID_AZIENDA_SANITARIA"))
      INDEX_RS_ASC(@"SEL$A813CFE0" "PA"@"SEL$101" ("GP_PRESTAZIONI_AGENDE"."ID_AGENDA"))
      INDEX(@"SEL$A813CFE0" "GP_TEMP_RA_PRESCRIZIONI"@"SEL$113"
              ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE" "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$A813CFE0" "PU"@"SEL$103" ("GP_PRESTAZIONI_UE"."ID_UNITA_EROGANTE"
              "GP_PRESTAZIONI_UE"."ID_PRESTAZIONE"))
      LEADING(@"SEL$A813CFE0" "AG"@"SEL$101" "UE"@"SEL$102" "RE"@"SEL$104" "PR"@"SEL$105" "AZ"@"SEL$106"
              "PA"@"SEL$101" "GP_TEMP_RA_PRESCRIZIONI"@"SEL$113" "PU"@"SEL$103")
      USE_NL(@"SEL$A813CFE0" "UE"@"SEL$102")
      USE_NL(@"SEL$A813CFE0" "RE"@"SEL$104")
      USE_NL(@"SEL$A813CFE0" "PR"@"SEL$105")
      USE_NL(@"SEL$A813CFE0" "AZ"@"SEL$106")
      USE_NL(@"SEL$A813CFE0" "PA"@"SEL$101")
      USE_NL(@"SEL$A813CFE0" "GP_TEMP_RA_PRESCRIZIONI"@"SEL$113")
      USE_NL(@"SEL$A813CFE0" "PU"@"SEL$103")
      NLJ_BATCHING(@"SEL$A813CFE0" "PU"@"SEL$103")
      INDEX_RS_ASC(@"SEL$6E8A1281" "R2"@"SEL$48" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$6E8A1281" "QD"@"SEL$46" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$6E8A1281" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$47"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$6E8A1281" "R2"@"SEL$48" "QD"@"SEL$46" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$47")
      USE_NL(@"SEL$6E8A1281" "QD"@"SEL$46")
      USE_NL(@"SEL$6E8A1281" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$47")
      NLJ_BATCHING(@"SEL$6E8A1281" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$47")
      INDEX_RS_ASC(@"SEL$3CF8A339" "R2"@"SEL$45" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$3CF8A339" "QD"@"SEL$37" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX_RS_ASC(@"SEL$3CF8A339" "QD"@"SEL$38" ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$3CF8A339" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$44"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$3CF8A339" "R2"@"SEL$45" "QD"@"SEL$37" "QD"@"SEL$38"
              "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$44")
      USE_NL(@"SEL$3CF8A339" "QD"@"SEL$37")
      USE_NL(@"SEL$3CF8A339" "QD"@"SEL$38")
      USE_NL(@"SEL$3CF8A339" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$44")
      NLJ_BATCHING(@"SEL$3CF8A339" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$44")
      INDEX_RS_ASC(@"SEL$0B56E548" "R2"@"SEL$36" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$0B56E548" "QD"@"SEL$28" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX_RS_ASC(@"SEL$0B56E548" "QD"@"SEL$29" ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$0B56E548" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$35"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$0B56E548" "R2"@"SEL$36" "QD"@"SEL$28" "QD"@"SEL$29"
              "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$35")
      USE_NL(@"SEL$0B56E548" "QD"@"SEL$28")
      USE_NL(@"SEL$0B56E548" "QD"@"SEL$29")
      USE_NL(@"SEL$0B56E548" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$35")
      NLJ_BATCHING(@"SEL$0B56E548" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$35")
      INDEX_RS_ASC(@"SEL$AA364CFE" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$27"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      INDEX_RS_ASC(@"SEL$580484EB" "R2"@"SEL$25" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$580484EB" "QD"@"SEL$23" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$580484EB" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$24"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$580484EB" "R2"@"SEL$25" "QD"@"SEL$23" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$24")
      USE_NL(@"SEL$580484EB" "QD"@"SEL$23")
      USE_NL(@"SEL$580484EB" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$24")
      NLJ_BATCHING(@"SEL$580484EB" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$24")
      INDEX_RS_ASC(@"SEL$9F6E67B7" "R2"@"SEL$22" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$9F6E67B7" "QD"@"SEL$20" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$9F6E67B7" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$21"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$9F6E67B7" "R2"@"SEL$22" "QD"@"SEL$20" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$21")
      USE_NL(@"SEL$9F6E67B7" "QD"@"SEL$20")
      USE_NL(@"SEL$9F6E67B7" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$21")
      NLJ_BATCHING(@"SEL$9F6E67B7" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$21")
      INDEX_RS_ASC(@"SEL$3B22806E" "R2"@"SEL$19" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$3B22806E" "QD"@"SEL$17" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      INDEX(@"SEL$3B22806E" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$18"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      LEADING(@"SEL$3B22806E" "R2"@"SEL$19" "QD"@"SEL$17" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$18")
      USE_NL(@"SEL$3B22806E" "QD"@"SEL$17")
      USE_NL(@"SEL$3B22806E" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$18")
      NLJ_BATCHING(@"SEL$3B22806E" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$18")
      INDEX_RS_ASC(@"SEL$87" "R2"@"SEL$87" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$007F748F" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$16"
              ("GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_AGENDA" "GP_QUESITI_DIAGNOSTICI_AGENDE"."ID_QUESITO_DIAGNOSTICO"
              ))
      INDEX(@"SEL$007F748F" "QSD"@"SEL$15" ("GP_QUESITI_DIAGNOSTICI"."ID_QUESITO_DIAGNOSTICO"))
      LEADING(@"SEL$007F748F" "GP_QUESITI_DIAGNOSTICI_AGENDE"@"SEL$16" "QSD"@"SEL$15")
      USE_NL(@"SEL$007F748F" "QSD"@"SEL$15")
      NLJ_BATCHING(@"SEL$007F748F" "QSD"@"SEL$15")
      INDEX_RS_ASC(@"SEL$85" "R2"@"SEL$85" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$79" "T2"@"SEL$79" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX_RS_ASC(@"SEL$4A493674" "DPA"@"SEL$77" ("GP_DISTRETTI_PA"."ID_PRESTAZIONE_AGENDA"
              "GP_DISTRETTI_PA"."ID_DISTRETTO_ANATOMICO"))
      INDEX_RS_ASC(@"SEL$29445BC0" "TE"@"SEL$6" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$29445BC0" "DA"@"SEL$4" ("GP_DISTRETTI_ANATOMICI"."ID_DISTRETTO_ANATOMICO"))
      INDEX(@"SEL$29445BC0" "DPA"@"SEL$5" ("GP_DISTRETTI_PA"."ID_PRESTAZIONE_AGENDA"
              "GP_DISTRETTI_PA"."ID_DISTRETTO_ANATOMICO"))
      LEADING(@"SEL$29445BC0" "TE"@"SEL$6" "DA"@"SEL$4" "DPA"@"SEL$5")
      USE_NL(@"SEL$29445BC0" "DA"@"SEL$4")
      USE_NL(@"SEL$29445BC0" "DPA"@"SEL$5")
      NLJ_BATCHING(@"SEL$29445BC0" "DPA"@"SEL$5")
      INDEX_RS_ASC(@"SEL$135E0F46" "TE"@"SEL$3" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      INDEX(@"SEL$135E0F46" "DA"@"SEL$1" ("GP_DISTRETTI_ANATOMICI"."ID_DISTRETTO_ANATOMICO"))
      INDEX(@"SEL$135E0F46" "DPA"@"SEL$2" ("GP_DISTRETTI_PA"."ID_PRESTAZIONE_AGENDA"
              "GP_DISTRETTI_PA"."ID_DISTRETTO_ANATOMICO"))
      LEADING(@"SEL$135E0F46" "TE"@"SEL$3" "DA"@"SEL$1" "DPA"@"SEL$2")
      USE_NL(@"SEL$135E0F46" "DA"@"SEL$1")
      USE_NL(@"SEL$135E0F46" "DPA"@"SEL$2")
      NLJ_BATCHING(@"SEL$135E0F46" "DPA"@"SEL$2")
      INDEX_RS_ASC(@"SEL$72" "T2"@"SEL$72" ("GP_TEMP_RA_PRESCRIZIONI"."ID_PRESCRIZIONE"
              "GP_TEMP_RA_PRESCRIZIONI"."ID_PRESTAZIONE" "GP_TEMP_RA_PRESCRIZIONI"."SEQ"))
      BITMAP_TREE(@"SEL$D99AE0CE" "DPA"@"SEL$74" AND(("GP_DISTRETTI_PA"."ID_DISTRETTO_ANATOMICO")
              ("GP_DISTRETTI_PA"."ID_PRESTAZIONE" "GP_DISTRETTI_PA"."FL_UTILIZZO")))
      INDEX_RS_ASC(@"SEL$05F70FAB" "PA"@"SEL$83" ("GP_PRESTAZIONI_AGENDE"."ID_AGENDA"
              "GP_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE"))
      INDEX_RS_ASC(@"SEL$05F70FAB" "MPA"@"SEL$82" ("GP_METODICHE_PRESTAZ_AGENDE"."ID_PRESTAZIONE_AGENDA"
              "GP_METODICHE_PRESTAZ_AGENDE"."DT_INIZIO_VALIDITA" "GP_METODICHE_PRESTAZ_AGENDE"."ID_METODICA"))
      LEADING(@"SEL$05F70FAB" "PA"@"SEL$83" "MPA"@"SEL$82")
      USE_NL(@"SEL$05F70FAB" "MPA"@"SEL$82")
      NO_ACCESS(@"SEL$30" "QM"@"SEL$30")
      NO_ACCESS(@"SEL$31" "from$_subquery$_230"@"SEL$31")
      INDEX_RS_ASC(@"SEL$33" "GP_QUESITI_DIAGNOSTICI"@"SEL$33"
              ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      USE_HASH_AGGREGATION(@"SEL$33")
      INDEX_RS_ASC(@"SEL$32" "GP_QUESITI_DIAGNOSTICI"@"SEL$32"
              ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      USE_HASH_AGGREGATION(@"SEL$32")
      NO_ACCESS(@"SEL$39" "QM"@"SEL$39")
      NO_ACCESS(@"SEL$40" "from$_subquery$_236"@"SEL$40")
      INDEX_RS_ASC(@"SEL$42" "GP_QUESITI_DIAGNOSTICI"@"SEL$42"
              ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      USE_HASH_AGGREGATION(@"SEL$42")
      INDEX_RS_ASC(@"SEL$41" "GP_QUESITI_DIAGNOSTICI"@"SEL$41"
              ("GP_QUESITI_DIAGNOSTICI"."CD_QUESITO_DIAGNOSTICO"))
      USE_HASH_AGGREGATION(@"SEL$41")
      INDEX_RS_ASC(@"SEL$3B9BC654" "CO"@"SEL$100" ("COMUNI_RD"."CD_COMUNE_ISTAT"))
      INDEX(@"SEL$3B9BC654" "PO"@"SEL$100" ("PROVINCIE_RD"."PROV_KEY_ID"))
      LEADING(@"SEL$3B9BC654" "CO"@"SEL$100" "PO"@"SEL$100")
      USE_NL(@"SEL$3B9BC654" "PO"@"SEL$100")
      NLJ_BATCHING(@"SEL$3B9BC654" "PO"@"SEL$100")
      INDEX_RS_ASC(@"SEL$111" "CO"@"SEL$111" ("COMUNI_RD"."CD_COMUNE_ISTAT"))
      INDEX_RS_ASC(@"SEL$110" "UP"@"SEL$110" ("UNITA_PRENOTANTI"."CD_UNITA_PRENOTANTE"))
      INDEX_RS_ASC(@"SEL$1BF21858" "GP"@"SEL$98" ("GP_GIORNI_PA"."ID_PRESTAZIONE_AGENDA"))
      INDEX_RS_ASC(@"SEL$1BF21858" "CA"@"SEL$98" ("GP_CALENDARI_PA"."ID_CALENDARIO_PA"))
      INDEX(@"SEL$1BF21858" "FR"@"SEL$99" ("GP_FASCE_RANGE_PA"."ID_GIORNO_PA"))
      LEADING(@"SEL$1BF21858" "GP"@"SEL$98" "CA"@"SEL$98" "FR"@"SEL$99")
      USE_NL(@"SEL$1BF21858" "CA"@"SEL$98")
      USE_NL(@"SEL$1BF21858" "FR"@"SEL$99")
      NLJ_BATCHING(@"SEL$1BF21858" "FR"@"SEL$99")
      INDEX_RS_ASC(@"SEL$054DEA08" "RP"@"SEL$97" ("GP_RUOLI_PRESTAZIONI_AGENDE"."ID_PRESTAZIONE_AGENDA"))
      INDEX(@"SEL$054DEA08" "RU"@"SEL$97" ("GP_RUOLI"."ID_RUOLO"))
      LEADING(@"SEL$054DEA08" "RP"@"SEL$97" "RU"@"SEL$97")
      USE_NL(@"SEL$054DEA08" "RU"@"SEL$97")
      NLJ_BATCHING(@"SEL$054DEA08" "RU"@"SEL$97")
      END_OUTLINE_DATA
  */
INTO GP_TEMP_RICERCA_AGENDE ( ID_PRESTAZIONE, ID_AZIENDA_SANITARIA, ID_PRESIDIO, ID_REPARTO, ID_UNITA_EROGANTE, CD_UNITA_PRENOTANTE, ID_AGENDA, ID_PRESTAZIONE_AGENDA, ID_COMBINATA, FL_VINCOLI_RISPETTATI )
--
SELECT
  DISTINCT
         PA.ID_PRESTAZIONE, PA.ID_AZIENDA_SANITARIA, PA.ID_PRESIDIO, PA.ID_REPARTO, PA.ID_UNITA_EROGANTE, PA.CD_UNITA_PRENOTANTE, PA.ID_AGENDA, PA.ID_PRESTAZIONE_AGENDA, PA.ID_COMBINATA, 'S'
  FROM GP_TEMP_RA_PRESCRIZIONI RA
  INNER JOIN V_GP_PRESTAZIONI_AGENDE PA ON RA.ID_PRESTAZIONE=PA.ID_PRESTAZIONE /* questa join appare fare tutta la differenza del mondo in innermost loop */
  INNER JOIN GP_AGENDE AG ON PA.ID_AGENDA=AG.ID_AGENDA
--
  WHERE ( EXISTS (
                   SELECT 0
                     FROM V_GP_DISTRETTI_PA DP
                     INNER JOIN GP_DISTRETTI_ANATOMICI DA ON DP.ID_DISTRETTO_ANATOMICO=DA.ID_DISTRETTO_ANATOMICO
                     INNER JOIN GP_TEMP_RA_PRESCRIZIONI TE ON DA.ID_DISTRETTO_ANATOMICO=TE.ID_DISTRETTO_ANATOMICO
                     WHERE
                           PA.ID_PRESTAZIONE_AGENDA=DP.ID_PRESTAZIONE_AGENDA
                       AND PA.ID_PRESTAZIONE=TE.ID_PRESTAZIONE
                       AND RA.ID_PRESCRIZIONE=TE.ID_PRESCRIZIONE
                       AND DP.CD_OPERATORE_LOGICO='U'
                       AND NOT EXISTS (
                                        SELECT 0
                                          FROM GP_TEMP_RA_PRESCRIZIONI T2
                                          WHERE
                                                T2.ID_PRESTAZIONE=TE.ID_PRESTAZIONE
                                            AND T2.ID_PRESCRIZIONE=TE.ID_PRESCRIZIONE
                                            AND T2.ID_DISTRETTO_ANATOMICO != TE.ID_DISTRETTO_ANATOMICO
                                            AND NOT EXISTS (
                                                             SELECT 0
                                                               FROM V_GP_DISTRETTI_PA D2
                                                               WHERE
                                                                     DP.ID_AGENDA=D2.ID_AGENDA
                                                                 AND D2.ID_PRESTAZIONE=T2.ID_PRESTAZIONE
                                                                 AND D2.ID_DISTRETTO_ANATOMICO=T2.ID_DISTRETTO_ANATOMICO
                                                                 AND D2.CD_OPERATORE_LOGICO='U'
                                                           )
                                      )
                 )
          OR ( NOT EXISTS ( 
                            SELECT 0
                              FROM V_GP_DISTRETTI_PA DP
                              INNER JOIN GP_DISTRETTI_ANATOMICI DA ON DP.ID_DISTRETTO_ANATOMICO=DA.ID_DISTRETTO_ANATOMICO
                              INNER JOIN GP_TEMP_RA_PRESCRIZIONI TE ON DA.ID_DISTRETTO_ANATOMICO=TE.ID_DISTRETTO_ANATOMICO
                              WHERE
                                    PA.ID_PRESTAZIONE_AGENDA=DP.ID_PRESTAZIONE_AGENDA
                                AND RA.ID_PRESCRIZIONE=TE.ID_PRESCRIZIONE
                                AND PA.ID_PRESTAZIONE=TE.ID_PRESTAZIONE
                                AND DP.CD_OPERATORE_LOGICO='D'
                          )
           AND NOT EXISTS (
                            SELECT 0
                              FROM V_GP_DISTRETTI_PA DP
                             WHERE
                                   PA.ID_PRESTAZIONE_AGENDA=DP.ID_PRESTAZIONE_AGENDA
                               AND DP.CD_OPERATORE_LOGICO='U'
                          )
             )
        )
--
    AND EXISTS ( SELECT 0 FROM GP_TEMP_RA_PRESCRIZIONI TE INNER JOIN GP_PRESTAZIONI_AGENDE PG ON TE.ID_PRESTAZIONE=PG.ID_PRESTAZIONE INNER JOIN ( SELECT PA.ID_PRESTAZIONE_AGENDA, PA.ID_AGENDA, NVL(MP.ID_METODICA, :B9 ) ID_METODICA FROM GP_PRESTAZIONI_AGENDE PA LEFT JOIN V_GP_METODICHE_PRESTAZ_AGENDE MP ON PA.ID_PRESTAZIONE_AGENDA=MP.ID_PRESTAZIONE_AGENDA ) MP ON PG.ID_PRESTAZIONE_AGENDA=MP.ID_PRESTAZIONE_AGENDA INNER JOIN GP_METODICHE ME ON MP.ID_METODICA=ME.ID_METODICA WHERE ME.ID_METODICA=NVL(TE.ID_METODICA, :B9 ) AND PA.ID_PRESTAZIONE_AGENDA=PG.ID_PRESTAZIONE_AGENDA AND RA.ID_PRESCRIZIONE=TE.ID_PRESCRIZIONE AND TE.ID_PRESTAZIONE=PA.ID_PRESTAZIONE AND NOT EXISTS ( SELECT 0 FROM GP_TEMP_RA_PRESCRIZIONI T2 WHERE T2.ID_PRESTAZIONE=TE.ID_PRESTAZIONE AND T2.ID_PRESCRIZIONE=TE.ID_PRESCRIZIONE AND T2.ID_METODICA!=TE.ID_METODICA AND NOT EXISTS ( SELECT 0 FROM ( SELECT PA.ID_PRESTAZIONE_AGENDA, PA.ID_PRESTAZIONE, PA.ID_AGENDA, NVL(MP.ID_METODICA, :B9 ) ID_METODICA FROM GP_PRESTAZIONI_AGENDE PA LEFT JOIN V_GP_METODICHE_PRESTAZ_AGENDE MP ON PA.ID_PRESTAZIONE_AGENDA=MP.ID_PRESTAZIONE_AGENDA ) M2 WHERE MP.ID_AGENDA=M2.ID_AGENDA AND M2.ID_PRESTAZIONE=T2.ID_PRESTAZIONE AND M2.ID_METODICA=T2.ID_METODICA ) ) )
--
    AND (
          CASE WHEN EXISTS (
                              SELECT 0
                                FROM GP_TEMP_RA_PRESCRIZIONI R2
                               WHERE R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE
                                 AND ID_QUESITO_DIAGNOSTICO IS NULL
                            )
               THEN CASE WHEN NOT EXISTS (
                                            SELECT 0
                                              FROM V_GP_QUESITI_DIAGNOSTICI QD
                                              INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO
                                             WHERE PA.ID_AGENDA=QA.ID_AGENDA AND QA.CD_OPERATORE_LOGICO='U'
                                         )
                         THEN 'S'
                         ELSE 'N'
                         END
                ELSE CASE WHEN EXISTS (
                                         SELECT 0
                                           FROM GP_TEMP_RA_PRESCRIZIONI R2
                                         WHERE R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE AND FL_AGENDE_SPECIALIZZATE='S'
                                      )
                     THEN CASE WHEN EXISTS (
                                              SELECT 0
                                                FROM GP_QUESITI_DIAGNOSTICI QD
                                                INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO
                                                INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO
                                              WHERE PA.ID_AGENDA=QA.ID_AGENDA
                                                AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE
                                                AND QA.CD_OPERATORE_LOGICO='U'
                                           )
                               THEN 'S'
                               ELSE 'N'
                               END
                     ELSE CASE WHEN ( EXISTS (
                                                SELECT 0
                                                  FROM GP_QUESITI_DIAGNOSTICI QD
                                                  INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO
                                                  INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO
                                                WHERE
                                                      PA.ID_AGENDA=QA.ID_AGENDA
                                                  AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE
                                                  AND QA.CD_OPERATORE_LOGICO='U'
                                             )
                                      OR ( NOT EXISTS (
                                                         SELECT 0
                                                           FROM GP_QUESITI_DIAGNOSTICI QD
                                                           INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO
                                                           INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO
                                                         WHERE
                                                               PA.ID_AGENDA=QA.ID_AGENDA
                                                           AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE
                                                           AND QA.CD_OPERATORE_LOGICO='D'
                                                      ) AND NOT EXISTS ( SELECT 0 FROM GP_QUESITI_DIAGNOSTICI QD INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO WHERE PA.ID_AGENDA=QA.ID_AGENDA AND QA.CD_OPERATORE_LOGICO='U' ) AND NOT EXISTS ( SELECT 0 FROM GP_QUESITI_DIAGNOSTICI QD INNER JOIN V_GP_QUESITO QDP ON QDP.CD_QUESITO_DIAGNOSTICO=QD.CD_QUESITO_DIAGNOSTICO_PADRE INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QDP.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO WHERE AG.ID_AGENDA=QA.ID_AGENDA AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE AND QA.CD_OPERATORE_LOGICO='D' ) ) OR ( EXISTS ( SELECT 0 FROM GP_QUESITI_DIAGNOSTICI QD INNER JOIN V_GP_QUESITO QDP ON QDP.CD_QUESITO_DIAGNOSTICO=QD.CD_QUESITO_DIAGNOSTICO_PADRE INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QDP.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO WHERE AG.ID_AGENDA=QA.ID_AGENDA AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE AND QA.CD_OPERATORE_LOGICO='U' ) AND NOT EXISTS ( SELECT 0 FROM GP_QUESITI_DIAGNOSTICI QD INNER JOIN V_GP_QUESITI_DIAGN_AGENDE QA ON QD.ID_QUESITO_DIAGNOSTICO=QA.ID_QUESITO_DIAGNOSTICO INNER JOIN GP_TEMP_RA_PRESCRIZIONI R2 ON QD.ID_QUESITO_DIAGNOSTICO=R2.ID_QUESITO_DIAGNOSTICO WHERE PA.ID_AGENDA=QA.ID_AGENDA AND R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE AND QA.CD_OPERATORE_LOGICO='D' ) ) ) THEN 'S' ELSE 'N' END END END ) = 'S'
--
   AND ( CASE WHEN PA.ID_COMBINATA IS NULL OR NOT EXISTS ( SELECT 0 FROM V_GP_PRESTAZIONI_AGENDE CO WHERE CO.ID_AGENDA=PA.ID_AGENDA AND CO.ID_PRESTAZIONE!=PA.ID_PRESTAZIONE AND CO.ID_COMBINATA IS NOT NULL AND CO.ID_COMBINATA=PA.ID_COMBINATA AND ID_PRESTAZIONE NOT IN ( SELECT ID_PRESTAZIONE FROM GP_TEMP_RA_PRESCRIZIONI ) ) THEN 'S' ELSE 'N' END ) = 'S'
--
   AND TO_NUMBER(NVL(:B8 , NVL(NR_ETA_MIN, 0))) BETWEEN NVL(PA.NR_ETA_MIN, 0) AND NVL(PA.NR_ETA_MAX, 9999999999)
--
   AND NVL(:B7 , NVL(PA.CD_SESSO, 'G')) = NVL(DECODE ( PA.CD_SESSO, 'G', NVL(:B7 , NVL(PA.CD_SESSO, 'G')), PA.CD_SESSO ), 'G')
--
   AND EXISTS ( SELECT 0 FROM GP_TEMP_RA_PRESCRIZIONI R2 WHERE R2.ID_PRESCRIZIONE=RA.ID_PRESCRIZIONE AND DECODE ( NVL(R2.FL_URGENZA, 'N'), 'N', NVL(PA.FL_URGENZA, 'N'), 'S' )=NVL(PA.FL_URGENZA, 'N') AND DECODE ( NVL(R2.FL_INDICATORE_PRIORITA_ALTA, 'N'), 'N', NVL(PA.FL_PRIORITA_ALTA, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ALTA, 'N') AND NVL(R2.TIPO_INVIANTE, NVL(PA.CD_INVIANTE, '0')) =NVL(PA.CD_INVIANTE, '0') AND ( CASE WHEN NVL(R2.FL_PRIORITA_ORDINARIA_D, 'N')|| NVL(R2.FL_PRIORITA_ORDINARIA_P, 'N')|| NVL(R2.FL_ACCESSO_PROGRAMMABILE, 'N')='SSS' THEN CASE WHEN DECODE ( NVL(R2.FL_PRIORITA_ORDINARIA_D, 'N'), 'N', NVL(PA.FL_PRIORITA_ORDINARIA_D, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ORDINARIA_D, 'N') OR DECODE ( NVL(R2.FL_PRIORITA_ORDINARIA_P, 'N'), 'N', NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N') OR DECODE ( NVL(R2.FL_ACCESSO_PROGRAMMABILE, 'N'), 'N', NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N'), 'S' )=NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N') THEN 'S' ELSE 'N' END ELSE CASE WHEN NVL(R2.FL_PRIORITA_ORDINARIA_P, 'N')|| NVL(R2.FL_ACCESSO_PROGRAMMABILE, 'N')='SS' THEN CASE WHEN DECODE ( NVL(R2.FL_PRIORITA_ORDINARIA_P, 'N'), 'N', NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N') OR DECODE ( NVL(R2.FL_ACCESSO_PROGRAMMABILE, 'N'), 'N', NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N'), 'S' )=NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N') THEN 'S' ELSE 'N' END ELSE CASE WHEN DECODE ( NVL(R2.FL_PRIORITA_ORDINARIA_D, 'N'), 'N', NVL(PA.FL_PRIORITA_ORDINARIA_D, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ORDINARIA_D, 'N') AND DECODE ( NVL(R2.FL_PRIORITA_ORDINARIA_P, 'N'), 'N', NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N'), 'S' )=NVL(PA.FL_PRIORITA_ORDINARIA_P, 'N') AND DECODE ( NVL(R2.FL_ACCESSO_PROGRAMMABILE, 'N'), 'N', NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N'), 'S' )=NVL(PA.FL_ACCESSO_PROGRAMMABILE, 'N') THEN 'S' ELSE 'N' END END END ) = 'S' )
--
   AND NVL(:B6 , PA.FL_SOSPENSIONE_TOTALE) =PA.FL_SOSPENSIONE_TOTALE
--
   AND NVL(:B5 , NVL(AG.CD_REGIME_EROGAZIONE, '1')) =NVL(AG.CD_REGIME_EROGAZIONE, '1')
--
   AND NVL(:B4 , PA.FL_PRENOTABILITA) =PA.FL_PRENOTABILITA 
--
   AND ( CASE WHEN :B4 ='S' THEN CASE WHEN EXISTS ( SELECT 0 FROM GP_RUOLI_PRESTAZIONI_AGENDE RP WHERE RP.ID_PRESTAZIONE_AGENDA=PA.ID_PRESTAZIONE_AGENDA AND RP.ID_RUOLO=NVL ( :B10 , RP.ID_RUOLO ) AND SYSDATE BETWEEN RP.DT_INIZIO_VALIDITA AND NVL (RP.DT_FINE_VALIDITA, SYSDATE+1) ) THEN 'S' ELSE 'N' END ELSE 'S' END ) = 'S'
--
   AND ( ( NOT EXISTS ( SELECT 0 FROM TABLE ( CAST(:B11 AS TYP_GP_AZIENDE_SANITARIE_LIST) ) ) AND NOT EXISTS ( SELECT 0 FROM TABLE ( CAST(:B12 AS TYP_GP_PRESIDI_LIST) ) ) AND NOT EXISTS ( SELECT 0 FROM TABLE ( CAST(:B13 AS TYP_GP_REPARTI_LIST) ) ) AND NOT EXISTS ( SELECT 0 FROM TABLE ( CAST(:B14 AS TYP_GP_UNITA_EROGANTI_LIST) ) ) ) OR ( PA.ID_AZIENDA_SANITARIA IN ( SELECT DISTINCT * FROM TABLE ( CAST(:B11 AS TYP_GP_AZIENDE_SANITARIE_LIST) ) ) OR PA.ID_PRESIDIO IN ( SELECT DISTINCT * FROM TABLE ( CAST(:B12 AS TYP_GP_PRESIDI_LIST) ) ) OR PA.ID_REPARTO IN ( SELECT DISTINCT * FROM TABLE ( CAST(:B13 AS TYP_GP_REPARTI_LIST) ) ) OR PA.ID_UNITA_EROGANTE IN ( SELECT DISTINCT * FROM TABLE ( CAST(:B14 AS TYP_GP_UNITA_EROGANTI_LIST) ) ) ) )
--
   AND ( :B3 IS NULL OR EXISTS ( SELECT 0 FROM COMUNI_RD CO INNER JOIN PROVINCIE_RD PR ON CO.PROV_KEY_ID=PR.PROV_KEY_ID INNER JOIN V_DC_COMUNI_ASL_STORICO CA ON CO.CD_COMUNE_ISTAT=CA.CD_COMUNE_ISTAT WHERE PA.CD_COMUNE=CO.CD_COMUNE_ISTAT AND PR.CD_PROVINCIA_ISTAT =:B3 AND ( :B15 IS NULL OR CA.CD_ASL=SUBSTR ( :B15 , 4 ) ) AND SYSDATE BETWEEN CO.DT_INIZIO_VALIDITA AND NVL(CO.DT_FINE_VALIDITA, SYSDATE+1) AND SYSDATE BETWEEN PR.DT_INIZIO_VALIDITA AND NVL(PR.DT_FINE_VALIDITA, SYSDATE+1) AND SYSDATE BETWEEN NVL(CA.DT_INIZIO_COMUNE, SYSDATE-1) AND NVL(CA.DT_FINE_COMUNE, SYSDATE+1) AND SYSDATE BETWEEN NVL(CA.DT_INIZIO_ASL, SYSDATE-1) AND NVL(CA.DT_FINE_ASL, SYSDATE+1) ) )
--
   AND ( :B2 IS NULL OR ( :B1 IS NOT NULL AND EXISTS ( SELECT 0 FROM DISTANZA_COMUNI DC WHERE DC.CD_COMUNE_ORIGINE=:B1 AND DC.CD_COMUNE_DESTINAZIONE=PA.CD_COMUNE AND DC.NETWORK <= :B2 * 1000 ) ) )
--
   AND EXISTS ( SELECT 0 FROM V_GP_CALENDARI_PA CA WHERE CA.ID_PRESTAZIONE_AGENDA=PA.ID_PRESTAZIONE_AGENDA AND NVL(CA.DT_FINE_CALENDARIO, :B16 ) >= :B16 )
/
@?/rdbms/admin/utlxplp
